---
deployment:
  tasks:
    - bundle install
    - bundle exec jekyll build
    - export DEPLOYPATH=/home/elmurjmz/public_html
    - rm -rf $DEPLOYPATH/*
    - /bin/cp -r ./_site/* $DEPLOYPATH/
    - /bin/chmod 755 $DEPLOYPATH
    - /bin/find $DEPLOYPATH -type f -exec /bin/chmod 644 {} +